services:
  web:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile.web
    image: web:latest
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 30
    volumes:
      - ./server:/code
      - /home/gdjones/ligtbm/ligtbm_storage/:/storage
      - static_volume:/staticfiles
      - media_volume:/mediafiles
      - ./server/core/static/core:/staticfiles/core
    env_file: ./.docker-env        
    expose:
      - 8000
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:10.5-alpine
    volumes:
      - /var/db/ligtbm/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=server-template

  nginx:
    build:
      context: buildfiles
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
      - ./server/core/static/core:/staticfiles/core
    ports:
      - 8080:80
    depends_on:
      - web
      - flower

  # runs on 5672 and 15672
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    command: rabbitmq-server -h rabbit
    env_file: ./.docker-env

  celery:
    image: web:latest
    entrypoint: /bin/sh -c "mkdir -p /storage/logs && celery -A server worker --statedb=/storage/state.db -E -l warning --logfile=/dev/null"
    volumes:
      - ./server:/code
      - /home/gdjones/ligtbm/ligtbm_storage/:/storage
    env_file: ./.docker-env        
    depends_on:
      - web
      - rabbitmq

  flower:
    image: web:latest
    entrypoint: celery -A server flower --port=5555 --url_prefix=flower --persistent=True --db=/storage/flower.db
    volumes:
      - ./server:/code
      - ./storage:/storage
    env_file: ./.docker-env
        
    depends_on:
      - rabbitmq
      - celery

volumes:
  static_volume:
  media_volume:
  postgres_data:

